version: '2'
services:
    banking-app:
        image: banking
        external_links:
            - banking-postgresql:postgresql
            - jhipster-registry:registry
        environment:
            - SPRING_PROFILES_ACTIVE=prod
            - SPRING_CLOUD_CONFIG_URI=http://admin:admin@registry:8761/config
            - SPRING_DATASOURCE_URL=jdbc:postgresql://postgresql:5432/banking
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
    banking-postgresql:
        extends:
            file: postgresql.yml
            service: banking-postgresql
    jhipster-registry:
        extends:
            file: jhipster-registry.yml
            service: jhipster-registry
